## 第二章 Pytorch基础知识
### 2.1 张量 
本章我们开始介绍PyTorch基础知识，我们从张量说起，建立起对数据的描述，再介绍张量的运算，最后再讲PyTorch中所有神经网络的核心包 autograd ，也就是自动微分，了解完这些内容我们就可以较好地理解PyTorch代码了。
#### 2.1.1 简介
几何代数中定义的张量是基于向量和矩阵的推广，比如我们可以将标量视为零阶张量，矢量可以视为一阶张量，矩阵就是二阶张量。
- 0维张量/**标量** 标量是一个数字
- 1维张量/**向量** 1维张量称为“向量”。
- 2维张量 2维张量称为**矩阵**
- 3维张量 公用数据存储在张量 时间序列数据 股价 文本数据 彩色图片(**RGB**)
张量是现代机器学习的基础。它的核心是一个数据容器，多数情况下，它包含数字，有时候它也包含字符串，但这种情况比较少。因此可以把它想象成一个数字的水桶。

这里有一些存储在各种类型张量的公用数据集类型：
- 3维 = 时间序列

- 4维 = 图像

- 5维 = 视频

例子：一个图像可以用三个字段表示：

(width, height, channel) = 3D

但是，在机器学习工作中，我们经常要处理不止一张图片或一篇文档——我们要处理一个集合。我们可能有10,000张郁金香的图片，这意味着，我们将用到4D张量：

(sample_size, width, height, channel) = 4D

在PyTorch中， torch.Tensor 是存储和变换数据的主要工具。如果你之前用过NumPy，你会发现 Tensor 和NumPy的多维数组非常类似。然而，Tensor 提供GPU计算和自动求梯度等更多功能，这些使 Tensor 这一数据类型更加适合深度学习。

#### 2.1.2 创建tensor
在接下来的内容中，我们将介绍几种创建tensor的方法。

   1.我们可以通过 torch.rand() 的方法，构造一个随机初始化的矩阵：

In [1]:
import torch
x = torch.rand(4,3)
print(x)

tensor([[0.4496, 0.7625, 0.2019],
        [0.4191, 0.7419, 0.9079],
        [0.7936, 0.3753, 0.6504],
        [0.9164, 0.4621, 0.6002]])


2.我们可以通过 torch.zeros() 构造一个矩阵全为 0，并且通过dtype设置数据类型为 long。

In [2]:
x = torch.zeros(4,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


3.我们可以通过 torch.tensor() 直接使用数据，构造一个张量：

In [3]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


4.基于已经存在的tensor，创建一个tensor

In [7]:
x = x.new_ones(4,3,dtype=torch.double)
# 创建一个新的tensor，返回的tensor默认具有相同的 torch.dtype和torch.device
# 也可以像之前的写法 x = torch.ones(4, 3, dtype=torch.double)
print(x)
x = torch.randn_like(x,dtype=torch.float)
print(x)
# 结果会有一样的size
# 获取它的维度信息
print(x.size())
print(x.shape)
# 返回的torch.Size其实是一个tuple，⽀持所有tuple的操作。
# 还有一些常见的构造Tensor的函数：

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.4823,  1.3848,  1.0903],
        [-0.8851, -1.1822,  0.0688],
        [-0.1351,  0.0219,  0.5621],
        [-1.3599,  0.8541,  1.9548]])
torch.Size([4, 3])
torch.Size([4, 3])


还有一些常见的构造Tensor的函数：

| 函数                | 功能                                              |
| ------------------- | :------------------------------------------------ |
| Tensor(sizes)       | 基础构造函数                                      |
| tensor(data)        | 类似于np.array                                    |
| ones(sizes)         | 全1                                               |
| zeros(sizes)        | 全0                                               |
| eye(sizes)          | 对角为1，其余为0                                  |
| arange(s,e,step)    | 从s到e，步长为step                                |
| linspace(s,e,steps) | 从s到e，均匀分成step份                            |
| rand/randn(sizes)   | rand是[0,1)均匀分布；randn是服从N(0，1)的正态分布 |
| normal(mean,std)    | 正态分布(均值为mean，标准差是std)                 |
| randperm(m)         | 随机排列                 |

#### 2.1.3 张量的操作
在接下来的内容中，我们将介绍几种常见的张量的操作方法：

1.加法操作：

In [14]:
# 1
y = torch.rand(4,3)
print(x+y)

#2
print(torch.add(x,y))

#3
result = torch.empty(6,3)
# print(result)
torch.add(x,y,out=result)
print(result)

#4
y.add_(x)
print(y)

tensor([[ 1.2621,  1.5037,  1.4080],
        [-0.8104, -1.0149,  0.1433],
        [ 0.7899,  0.1024,  1.3994],
        [-0.8468,  1.2784,  2.8866]])
tensor([[ 1.2621,  1.5037,  1.4080],
        [-0.8104, -1.0149,  0.1433],
        [ 0.7899,  0.1024,  1.3994],
        [-0.8468,  1.2784,  2.8866]])
tensor([[ 1.2621,  1.5037,  1.4080],
        [-0.8104, -1.0149,  0.1433],
        [ 0.7899,  0.1024,  1.3994],
        [-0.8468,  1.2784,  2.8866]])
tensor([[ 1.2621,  1.5037,  1.4080],
        [-0.8104, -1.0149,  0.1433],
        [ 0.7899,  0.1024,  1.3994],
        [-0.8468,  1.2784,  2.8866]])


c:\ProgramData\Anaconda3\envs\torch_py37\lib\site-packages\ipykernel_launcher.py:11: UserWarning: An output with one or more elements was resized since it had shape [6, 3], which does not match the required output shape [4, 3].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  ..\aten\src\ATen\native\Resize.cpp:23.)
  # This is added back by InteractiveShellApp.init_path()


2.索引操作：（类似于numpy）
需要注意的是：索引出来的结果与原数据共享内存，修改一个，另一个会跟着修改。如果不想修改，可以考虑使用copy()等方法

In [16]:
print(x)
print(x[:,1])

tensor([[ 0.4823,  1.3848,  1.0903],
        [-0.8851, -1.1822,  0.0688],
        [-0.1351,  0.0219,  0.5621],
        [-1.3599,  0.8541,  1.9548]])
tensor([ 1.3848, -1.1822,  0.0219,  0.8541])


In [19]:
y = x[0,:]
print(y)
y += 1
print(y)
print(x[0,:]) # 源tensor也被改了了

tensor([1.4823, 2.3848, 2.0903])
tensor([2.4823, 3.3848, 3.0903])
tensor([2.4823, 3.3848, 3.0903])


改变大小:如果你想改变一个 tensor 的大小或者形状，你可以使用 torch.view：

In [20]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) # -1是指这一维的维数由其他维度决定
print(x.size(),y.size(),z.size())
# 注意 view() 返回的新tensor与源tensor共享内存(其实是同一个tensor)，
# 也即更改其中的一个，另外一个也会跟着改变。(顾名思义，view仅仅是改变了对这个张量的观察⻆度)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [21]:
x += 1
print(x)
print(y) # 也加了了1

tensor([[ 3.8405,  0.8871,  0.4626,  1.9604],
        [ 2.1525,  0.9405,  3.2582,  1.7831],
        [ 3.0181,  1.3975,  2.3614,  1.4624],
        [ 1.3257,  0.7545,  1.7155, -0.1274]])
tensor([ 3.8405,  0.8871,  0.4626,  1.9604,  2.1525,  0.9405,  3.2582,  1.7831,
         3.0181,  1.3975,  2.3614,  1.4624,  1.3257,  0.7545,  1.7155, -0.1274])


所以如果我们想返回一个真正新的副本(即不共享内存)该怎么办呢？Pytorch还提供了一 个 reshape() 可以改变形状，但是此函数并不能保证返回的是其拷贝，所以不推荐使用。推荐先用 clone 创造一个副本然后再使用 view 。

In [23]:
# 注意：使用 clone 还有一个好处是会被记录在计算图中，即梯度回传到副本时也会传到源 Tensor 。
# 如果你有一个元素 tensor ，使用 .item() 来获得这个 value：
x = torch.randn(1)
print(type(x))
print(x.item())
print(type(x.item()))
# PyTorch中的 Tensor 支持超过一百种操作，包括转置、索引、切片、数学运算、线性代数、随机数等等，可参考官方文档。

<class 'torch.Tensor'>
0.6912593841552734
<class 'float'>


#### 2.1.4 广播机制
当对两个形状不同的 Tensor 按元素运算时，可能会触发广播(broadcasting)机制：先适当复制元素使这两个 Tensor 形状相同后再按元素运算。

In [24]:
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)
# 由于 x 和 y 分别是1行2列和3行1列的矩阵，如果要计算 x + y ，
# 那么 x 中第一行的2个元素被广播 (复制)到了第二行和第三行，
# ⽽ y 中第⼀列的3个元素被广播(复制)到了第二列。如此，就可以对2 个3行2列的矩阵按元素相加。

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


### 2.2 自动求导
PyTorch 中，所有神经网络的核心是 `autograd `包。autograd包为张量上的所有操作提供了自动求导机制。它是一个在运行时定义 ( define-by-run ）的框架，这意味着反向传播是根据代码如何运行来决定的，并且每次迭代可以是不同的。

`torch.Tensor `是这个包的核心类。如果设置它的属性` .requires_grad` 为 `True`，那么它将会追踪对于该张量的所有操作。当完成计算后可以通过调用` .backward()`，来自动计算所有的梯度。这个张量的所有梯度将会自动累加到`.grad`属性。

注意：在 y.backward() 时，如果 y 是标量，则不需要为 backward() 传入任何参数；否则，需要传入一个与 y 同形的Tensor。

要阻止一个张量被跟踪历史，可以调用`.detach()`方法将其与计算历史分离，并阻止它未来的计算记录被跟踪。为了防止跟踪历史记录(和使用内存），可以将代码块包装在 `with torch.no_grad(): `中。在评估模型时特别有用，因为模型可能具有 `requires_grad = True` 的可训练的参数，但是我们不需要在此过程中对他们进行梯度计算。

还有一个类对于`autograd`的实现非常重要：`Function`。`Tensor `和` Function` 互相连接生成了一个无环图 (acyclic graph)，它编码了完整的计算历史。每个张量都有一个`.grad_fn`属性，该属性引用了创建 `Tensor `自身的`Function`(除非这个张量是用户手动创建的，即这个张量的`grad_fn`是 `None` )。下面给出的例子中，张量由用户手动创建，因此grad_fn返回结果是None。

In [25]:
from __future__ import print_function
import torch
x = torch.randn(3,3,requires_grad=True)
print(x.grad_fn)

None


如果需要计算导数，可以在 `Tensor` 上调用 `.backward()`。如果` Tensor` 是一个标量(即它包含一个元素的数据），则不需要为 `backward() `指定任何参数，但是如果它有更多的元素，则需要指定一个`gradient`参数，该参数是形状匹配的张量。

创建一个张量并设置`requires_grad=True`用来追踪其计算历史

In [26]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


对这个张量做一次运算：



In [27]:
y = x**2
print(y)

tensor([[1., 1.],
        [1., 1.]], grad_fn=<PowBackward0>)


y是计算的结果，所以它有`grad_fn`属性。



In [28]:
print(y.grad_fn)


对 y 进行更多操作



In [29]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<MulBackward0>) tensor(3., grad_fn=<MeanBackward0>)


`.requires_grad_(...) `原地改变了现有张量的`requires_grad`标志。如果没有指定的话，默认输入的这个标志是` False`。

In [30]:
a = torch.randn(2, 2) # 缺失情况下默认 requires_grad = False
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


梯度

现在开始进行反向传播，因为` out` 是一个标量，因此`out.backward()`和` out.backward(torch.tensor(1.))` 等价。

In [31]:
out.backward()

输出导数 `d(out)/dx`

In [32]:
print(x.grad)


tensor([[3., 3.],
        [3., 3.]])


数学上，若有向量函数

$$ 
\vec{y}=f(\vec{x})
$$

，那么 
$$ 
\vec{y}\)
$$ 
关于 
$$
\(\vec{x} 

$$
的梯度就是一个雅可比矩阵： \( J=\left(\begin{array}{ccc}\frac{\partial y_{1}}{\partial x_{1}} & \cdots & \frac{\partial y_{1}}{\partial x_{n}} \\ \vdots & \ddots & \vdots \\ \frac{\partial y_{m}}{\partial x_{1}} & \cdots & \frac{\partial y_{m}}{\partial x_{n}}\end{array}\right) \) 而 torch.autograd 这个包就是用来计算一些雅可比矩阵的乘积的。例如，如果 \(v\) 是一个标量函数 \(l = g(\vec{y})\) 的梯度： \( v=\left(\begin{array}{lll}\frac{\partial l}{\partial y_{1}} & \cdots & \frac{\partial l}{\partial y_{m}}\end{array}\right) \) 由链式法则，我们可以得到： \( v J=\left(\begin{array}{lll}\frac{\partial l}{\partial y_{1}} & \cdots & \frac{\partial l}{\partial y_{m}}\end{array}\right)\left(\begin{array}{ccc}\frac{\partial y_{1}}{\partial x_{1}} & \cdots & \frac{\partial y_{1}}{\partial x_{n}} \\ \vdots & \ddots & \vdots \\ \frac{\partial y_{m}}{\partial x_{1}} & \cdots & \frac{\partial y_{m}}{\partial x_{n}}\end{array}\right)=\left(\begin{array}{lll}\frac{\partial l}{\partial x_{1}} & \cdots & \frac{\partial l}{\partial x_{n}}\end{array}\right) \)

注意：grad在反向传播过程中是累加的(accumulated)，这意味着每一次运行反向传播，梯度都会累加之前的梯度，所以一般在反向传播之前需把梯度清零。

In [33]:
# 再来反向传播⼀一次，注意grad是累加的
out2 = x.sum()
out2.backward()
print(x.grad)

out3 = x.sum()
x.grad.data.zero_()
out3.backward()
print(x.grad)

tensor([[4., 4.],
        [4., 4.]])
tensor([[1., 1.],
        [1., 1.]])


现在我们来看一个雅可比向量积的例子：



In [34]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x * 2
i = 0
while y.data.norm() < 1000:
    y = y * 2
    i = i + 1
print(y)
print(i)

tensor([ 0.9808, -0.3108, -1.1110], requires_grad=True)
tensor([ 1004.3168,  -318.2760, -1137.6276], grad_fn=<MulBackward0>)
9


在这种情况下，`y `不再是标量。`torch.autograd` 不能直接计算完整的雅可比矩阵，但是如果我们只想要雅可比向量积，只需将这个向量作为参数传给 `backward：`

In [35]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


也可以通过将代码块包装在` with torch.no_grad():` 中，来阻止 autograd 跟踪设置了`.requires_grad=True`的张量的历史记录。

In [36]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


如果我们想要修改 tensor 的数值，但是又不希望被 autograd 记录(即不会影响反向传播)， 那么我们可以对 tensor.data 进行操作。



In [37]:
x = torch.ones(1,requires_grad=True)

print(x.data) # 还是一个tensor
print(x.data.requires_grad) # 但是已经是独立于计算图之外

y = 2 * x
x.data *= 100 # 只改变了值，不会记录在计算图，所以不会影响梯度传播

y.backward()
print(x) # 更改data的值也会影响tensor的值 
print(x.grad)

tensor([1.])
False
tensor([100.], requires_grad=True)
tensor([2.])


### 2.3 并行计算简介
在利用PyTorch做深度学习的过程中，可能会遇到数据量较大无法在单块GPU上完成，或者需要提升计算速度的场景，这时就需要用到并行计算。本节让我们来简单地了解一下并行计算的基本概念和主要实现方式，具体的内容会在课程的第二部分详细介绍。

#### 2.3.1 为什么要做并行计算

`CUDA`是我们使用GPU的提供商——NVIDIA提供的GPU并行计算框架。对于GPU本身的编程，使用的是`CUDA`语言来实现的。但是，在我们使用PyTorch编写深度学习代码时，使用的`CUDA`又是另一个意思。在PyTorch使用 `CUDA`表示要开始要求我们的模型或者数据开始使用GPU了。

在编写程序中，当我们使用了 `.cuda` 时，其功能是让我们的模型或者数据迁移到GPU当中，通过GPU开始计算。

注：

1. 我们使用GPU时使用的是.cuda而不是使用.gpu。这是因为当前GPU的编程接口采用CUDA，但是市面上的GPU并不是都支持CUDA，只有部分NVIDIA的GPU才支持，AMD的GPU编程接口采用的是OpenGL，在现阶段PyTorch并不支持。
2. 数据在GPU和CPU之间进行传递时会比较耗时，应当尽量避免。
3. GPU运算很快，但是在使用简单的操作时，我们应该尽量使用CPU去完成。
4. 当我们的服务器上有多个GPU，我们应该指明我们使用的GPU是哪一块，如果我们不设置的话，tensor.cuda()方法会默认将tensor保存到第一块GPU上，等价于tensor.cuda(0)，这将会导致爆出`out of memory`的错误。我们可以通过以下两种方式继续设置。


1. ```
    #设置在文件最开始部分
   import os
   os.environ["CUDA_VISIBLE_DEVICE"] = "2" # 设置默认的显卡
   ```

2. ```
    CUDA_VISBLE_DEVICE=0,1 python train.py # 使用0，1两块GPU
   ```

In [ ]:
 #设置在文件最开始部分
# import os
# os.environ["CUDA_VISIBLE_DEVICE"] = "2" # 设置默认的显卡

In [ ]:
# CUDA_VISBLE_DEVICE =0,1 python train.py # 使用0，1两块GPU


#### 2.3.3 常见的并行的方法：


**网络结构分布到不同的设备中(Network partitioning)**

在刚开始做模型并行的时候，这个方案使用的比较多。其中主要的思路是，将一个模型的各个部分拆分，然后将不同的部分放入到GPU来做不同任务的计算。其架构如下

![](2022-05-18-00-30-51.png)

**同一层的任务分布到不同数据中(Layer-wise partitioning)**

第二种方式就是，同一层的模型做一个拆分，让不同的GPU去训练同一层模型的部分任务。其架构如下

![](2022-05-18-00-31-55.png)

这样可以保证在不同组件之间传输的问题，但是在我们需要大量的训练，同步任务加重的情况下，会出现和第一种方式一样的问题。

**不同的数据分布到不同的设备中，执行相同的任务(Data parallelism)**

第三种方式有点不一样，它的逻辑是，我不再拆分模型，我训练的时候模型都是一整个模型。但是我将输入的数据拆分。所谓的拆分数据就是，同一个模型在不同GPU中训练一部分数据，然后再分别计算一部分数据之后，只需要将输出的数据做一个汇总，然后再反传。其架构如下：

![](2022-05-18-00-32-52.png)

这种方式可以解决之前模式遇到的通讯问题。



PS:现在的主流方式是数据并行的方式(Data parallelism)

